name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_COMMIT: "False"
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "style(wakatime): update metrics"
          COMMIT_USERNAME: "EniumAction"
          COMMIT_SINGLE: "True"
          LOCALE: "en"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          SYMBOL_VERSION: "1"
